services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - ./volumes/open-webui:/app/backend/data
    ports:
      - 4000:8080
    environment:
      - GLOBAL_LOG_LEVEL=INFO
      - WEBUI_NAME=Private A.I.
      - WEBUI_SECRET_KEY=
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - AUDIO_STT_ENGINE=openai
      - AUDIO_STT_MODEL=tiny-int8
      - AUDIO_STT_OPENAI_API_BASE_URL=http://192.168.1.6:10300/v1
      - AUDIO_STT_OPENAI_API_KEY=
      - AUDIO_TTS_OPENAI_API_BASE_URL=http://192.168.1.6:10200/v1
      - AUDIO_TTS_OPENAI_API_KEY=
    restart: unless-stopped

