nfs-server:
  image: gists/nfs-server
  container_name: nfs-server
  ports:
    - 2049:2049
  cap_add:
    - SYS_ADMIN
    - SETPCAP
  security_opt:
    - apparmor:unconfined
  env_file:
    - .env 
  volumes:
    - /mnt/nas/filestash:/nfs-share
  restart: unless-stopped

