version: '3'

services:
  uptime:
    container_name: uptime
    image: louislam/uptime-kuma:alpine
    ports:
      - 3001:3001
    restart: unless-stopped
    volumes:
      - ./volumes/data:/app/data
