services:
  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:rocm
    ports:
      - "11434:11434"
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - HSA_OVERRIDE_GFX_VERSION=9.0.0
      - HSA_ENABLE_SDMA=0
      - HSA_ENABLE_PEER_SDMA=0
      - HSA_XNACK=0
      - OLLAMA_KEEP_ALIVE=300
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_FLASH_ATTENTION=false
      - OLLAMA_KV_CACHE_TYPE=f16
      - OLLAMA_MAX_QUEUE=10
      - OLLAMA_CONTEXT_LENGTH=32000
      - OLLAMA_MULTIUSER_CACHE=true
      - OLLAMA_NEW_ENGINE=true

