services:
  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=600
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_NUM_PARALLEL=0
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_MAX_QUEUE=0
      - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_MULTIUSER_CACHE=true
      - OLLAMA_NEW_ENGINE=true
      - OLLAMA_MAX_VRAM=7000
      - OLLAMA_GPU_OVERHEAD=0
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
