services:
  ollama:
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:rocm
    ports:
      - "11434:11434"
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp:unconfined
    volumes:
      - ./volumes/ollama:/root/.ollama
    environment:
      - HSA_ENABLE_SDMA=1
      - HSA_ENABLE_PEER_SDMA=1
      - HSA_XNACK=1
      - OLLAMA_KEEP_ALIVE=600
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_FLASH_ATTENTION=true
      - OLLAMA_MAX_QUEUE=10
      - OLLAMA_CONTEXT_LENGTH=4096
      - OLLAMA_MULTIUSER_CACHE=true
      - OLLAMA_NEW_ENGINE=true
      - OLLAMA_MAX_VRAM=0
